[toolchain]

[features]
resolved = true
skip-lint = false

[programs.localnet]
hello = "AZutZ4iRx3fX86bU4gGEkxLbQGFPxj6ZQuEDokvTxVjM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo no tests"
